apiVersion: v1
kind: Secret
metadata:
  labels:
    app: {{.Values.appTest | quote}}
    kubernetes.io/version: "1.17"
  name: build-robot-secret
  annotations:
    kubernetes.io/service-account.name: build-robot
type: kubernetes.io/service-account-token