apiVersion: v1
kind: Namespace
metadata:
  name: tools
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: platformengineering
  namespace: tools
spec:
  selector:
    matchLabels:
      app: platformengineering
  replicas: 1
  template:
    metadata:
      labels:
        app: platformengineering
    spec:
      containers:
      - name: platformengineering
        image: backstage/backend:latest
        ports:
        - containerPort: 3030
        env:
        - name: MONGO_URI
          value: mongodb://mongodb:27017/backstage
        - name: ELASTICSEARCH_URLS
          value: http://elasticsearch:9200
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.12.0
        ports:
        - containerPort: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: platformengineering
  namespace: tools
spec:
  selector:
    app: platformengineering
  ports:
  - name: http
    port: 3030
    targetPort: 3030
  type: ClusterIP
