apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}
spec:
  type: ClusterIP
  ports:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: {{.Values.name}}
