apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-canary
spec:
  type: {{.Values.serviceType}}
  ports:
  - name: http-canary
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: {{.Values.name}}
    harness.io/track: canary
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.name}}-stable
spec:
  type: {{.Values.serviceType}}
  ports:
  - name: http-stable
    port: 8080
    targetPort: http
    protocol: TCP
  selector:
    app: {{.Values.name}}
    harness.io/track: stable
